FlowM2M/AwaLWM2M

ci/jenkins.sh, ci/lcov_cobertura.py
This patch adds support for the Cobertura Jenkins plugin, which provides useful visualisation of code coverage, and can enforce thresholds that can be used to control the CI builds. Gcov/lcov output is converted to a compatible format by a third-party python script, used and redistributed under the Apache 2.0 license.
Ref: N/A
=> Add support for the Cobertura code-coverage Jenkins plugin.

api/tests-static/test_client.cc, core/src/bootstrap/lwm2m_bootstrap_core.c, core/src/bootstrap/lwm2m_core.h, core/src/client/lwm2m_client_core.c, core/src/client/lwm2m_client_xml_handlers.c, core/src/client/lwm2m_core.h, core/src/client/lwm2m_security_object.c, core/src/client/lwm2m_server_object.c, core/src/client/lwm2m_static.c, core/src/common/lwm2m_debug.c, core/src/common/lwm2m_definition.h, core/src/common/lwm2m_object_store.c, core/src/common/lwm2m_object_store.h, core/src/common/lwm2m_observers.c, core/src/common/lwm2m_tree_builder.c, core/src/server/lwm2m_core.h, core/tests/test_object_store_interface.cc
Remove Lwm2mCore_GetResourceInstanceLength and rework Lwm2mCore_GetResourceInstanceValue in order to support Static API handlers.
=> Refactor get length into read resource

core/src/common/lwm2m_debug.c
This patch fixes an issue where non-info log messages, such as warnings and errors, do not display their source filename and line number when the API is in verbose mode.
Ref: N/A
=> Fix missing filenames and line numbers with non-info log messages.

api/src/ipc.h, api/src/session_common.c
Automated tests show occasional failures due to IPC session connect timeouts at the start of some tests. This may be due to overloading of the test system preventing IPC connection from completing within the 5 seconds provided. Doubling this timeout should reduce the incidence of such failures.
=> Double IPC Session Connect timeout to 10 seconds.

core/src/client/lwm2m_connectivity_object.c, core/src/server/lwm2m_server_xml_handlers.c, tools/tests/gtest/test_tools_common.cc, tools/tools_common.c
This patch fixes undefined behaviour when an attempt is made to create an instance of object 7, and then a read attempt is made on /7/0/6. In addition, this also adds tests for null pointers in tools_common functions that can lead to a crash with bad tools syntax (e.g. awa-server-write -c IMG -o=/7/0).
Ref: FLOWDM-522
=> Fix error when attempting to create instance of object 7

doc/developer_guide.md, doc/example_app.md, doc/userguide.md
Editing documentation to differentiate the Awa LightweightM2M product. We're in the habit of referring to Awa LightweightM2M as Awa LWM2M. LWM2M is an OMA affectation and not part of our product name. Since Awa LIghtweightM2M is an implementation of the OMA spec it needs to be differentiated, not lumped in with everything else. May seem picky - but people won't discover the project if they don't use it's correct name.
=> Editing documentation to differentiate the Awa LightweightM2M product

core/src/common/lwm2m_tlv.c, core/tests/test_tlv.cc
Fix out of bounds memory access picked up by coverity
5 bytes were being allocated for the TLV header, which works in most
cases. But in the case where a 16 bit identifier is used with a
24 bit length the resulting header will be 6 bytes and overflow.
=> Fix TLV buffer overflow

doc/userguide.md
The user guide doc structure isn't as the table of contents suggests. Rather than restructure the doc I've added links back to the table of contents at the end of each section. I'll restructure it in the future if any significant additions are made.
=> Document navigation

api/tests/test_client_define_defaults.cc, api/tests/test_subscribe_operation.cc, api/tests/test_write_operation.cc, core/src/client/lwm2m_client_core.c, core/src/client/lwm2m_client_xml_handlers.c, core/src/client/lwm2m_core.h, core/src/server/lwm2m_server_xml_handlers.c, core/tests/test_tlv.cc
Added replace flag to Lwm2mCore_Delete to allow delete on resources in the
case we are doing a PUT on a resource (In all other cases, only deletion on
the object / object instance levels are allowed).
Sensible default allocation no longer adds a resource instance to array
resources (Arrays should be empty by default).
Enabled Objectlink array client define defaults tests.
ref: FLOWDM-636
=> Fixed PUT / POST handling on multiple instance and mandatory resources.

.travis.yml, Makefile, tools/Makefile
This patch fixes the issue where failing to run python tests does not cause build to fail. It also adds the required components to the TravisCI container to run the Python tool tests successfully.
=> Fix support for Python tools tests.

CMakeLists.txt, api/tests-static/CMakeLists.txt, core/CMakeLists.txt, core/src/bootstrap/CMakeLists.txt, core/src/client/CMakeLists.txt, core/src/common/CMakeLists.txt, core/src/common/lwm2m_serdes.c, core/src/server/CMakeLists.txt, core/tests/CMakeLists.txt, lib/CMakeLists.txt, lib/jsmn/CMakeLists.txt
This patch provides a mechanism to omit JSON support (and libjsmn dependency). By default, JSON support is included.
To build without JSON support, set the relevant CMAKE option with:
make CMAKE_OPTIONS=-DWITH_JSON=OFF
Ref: FLOWDM-693
=> Provide build-time switch to disable JSON support.

api/include/awa/static.h, api/tests-static/test_client.cc, core/src/client/lwm2m_static.c
The opaque data type is a little different from all the others
being that it is variable length (and doesn't provide another
mechanism to determine it's length, i.e NULL terminated)
This means we need to store a provide a pointer to data, as
well as a pointer to store the length to the
AwaStaticClient_RegisterResourceWithPointer() function.
Now we could simply pass in a pointer to a AwaOpaque data type,
but this is setup for dynamic memory allocation, which goes
against the whole point of the WithPointer() function.
So, to allow variable length opaque data types to be statically
allocated, I have added the AWA_OPAQUE macro.
This macro can be used in place of a variable declaration.
for example:
AWA_OPAQUE(opaque, 32);
strcpy(opaque.Data, "hello");
opaque.Size = strlen("hello"); …
=> Add AWA_OPAQUE macro to Awa static API

api/include/awa/static.h, api/tests-static/test_client.cc, core/src/client/lwm2m_client_core.c, core/src/client/lwm2m_static.c, core/src/common/lwm2m_result.c, core/src/common/lwm2m_result.h
One working test for AwaStaticClient_ResourceChanged is in
place but it needs to be cleaned up and parameterised.
Added a temporary mapping between Lwm2mResult and AwaLwm2mError
although these enums should really be combined.
Renamed some wrongly spelt variables in test_client.cc
=> Added AwaStaticClient_ResourceChanged

api/tests-static/test_client.cc, core/src/client/lwm2m_static.c, core/src/common/lwm2m_definition.h
AwaStaticClient_RegisterResourceWithPointerArray allows for an array
of pointers to be used instead of a base pointer + offset. This may
be useful when resources are stored at fixed memory locations.
=> Add support for AwaStaticClient_RegisterResourceWithPointerArray()

api/tests/CMakeLists.txt, api/tests/test_client_define_defaults.cc, api/tests/test_define_common.cc, api/tests/test_server_define_defaults.cc, core/src/client/lwm2m_client_core.c, core/src/server/lwm2m_server_xml_handlers.c
Now if an internal error occurs, an AwaError_Internal tag will be added to the
response for that object / object instance node.
=> Fixed defaults not being added correctly to CoAP create packet from server XML handler

api/src/observe_operation.c
If the memory was changed at any time before calling
AwaServerObserveOperation_Perform, the request was sent
with an unintended Client ID.
=> Fixed AwaServerObservation_New not allocating memory for ClientID.

core/src/client/lwm2m_client_core.c
Signed-off-by: Sean Kelly <Sean.Kelly@imgtec.com>
=> Refactor Core handlers and add error messages for handlers

api/tests/test_write_operation.cc, core/src/server/lwm2m_server_xml_handlers.c, tools/tests/python/test_awa_server.py, tools/tests/python/test_awa_server_write.py
Fixed a bug in an if statement that causes optional resources to be populated with "sensible default values" in a lwm2m write operation. This also includes a test case that highlights the issue.
=> Fix bug in server where creating an object will populate optional resources.

doc/starters_guide.md
Directory name 'bootstrapd' typo fixed. Now says 'bootstrap'.
=> Update starters_guide.md - typo fixed

api/src/string_array.c, api/src/value.c, core/src/client/lwm2m_client_xml_handlers.c, lib/xml/xmlparser.c, lib/xml/xmltree.c
=> Fix some coverity issues raised in April 11th scan.

api/include/awa/error.h, api/src/lwm2m_error.c, api/tests-static/support/static_api_support.h, api/tests-static/test_static_api_with_pointer.cc, core/src/common/coap_abstraction_libcoap.c, core/src/server/lwm2m_server_xml_handlers.c
When a CoAP transaction times out, the LWM2MError field is now
populated with the AwaLWM2MError_Timeout code like so:
`
<Response>
<Type>Write</Type>
<Code>200</Code>
<Content>
<Clients>
<Client>
<ID>TestIMG1</ID>
<Objects>
<Object>
<ID>7998</ID>
<ObjectInstance>
<ID>0</ID>
<Resource>
<ID>1</ID>
<Result>
<Error>AwaError_LWM2MError</Error>
<LWM2MError>AwaLWM2MError_Timeout</LWM2MError>
</Result>
</Resource>
</ObjectInstance>
</Object>
</Objects>
</Client>
</Clients>
</Content>
</Response>
`
=> Return AwaLWM2MError_Timeout via IPC when a CoAP request timesout

api/tests/test_server_define_defaults.cc, core/src/server/lwm2m_server_xml_handlers.c
Added test for creating an Opaque via the server API with an empty
default value (simulating what would be used for provisioning).
=> Fixed xmlif_AddDefaultsForMissingMandatoryValues not returning -1 on error.

api/examples/CMakeLists.txt, api/examples/tutorials/CMakeLists.txt, api/examples/tutorials/static-client-tutorial2.c, api/examples/tutorials/static-client-tutorial3.c, api/include/awa/static.h, api/tests-static/CMakeLists.txt, api/tests-static/support/static_api_support.h, api/tests-static/test_static_api.cc, api/tests-static/test_static_api_get_resource_instance_pointer.cc, api/tests-static/test_static_api_get_resource_instance_pointer_deprecated.cc, api/tests-static/test_static_api_handlers.cc, api/tests-static/test_static_api_handlers_deprecated.cc, api/tests-static/test_static_api_with_pointer.cc, api/tests-static/test_static_api_with_pointer_deprecated.cc, core/src/client/lwm2m_static.c, core/src/common/lwm2m_definition.c, core/src/common/lwm2m_definition.h, doc/developer_guide.md
These changes are intended to improve consistency with the Gateway API, and separate the concerns of Object/Resource _definition_ from how the entity is managed or stored. This results in the deprecation of some existing API functions. These deprecated functions will be removed after 0.1.8 has been released.
Also includes a minor documentation update by reserving a section for "Best Practices".
=> Static API changes

Makefile, api/CMakeLists.txt, api/examples/tutorials/Makefile, api/src/CMakeLists.txt, core/src/bootstrap/CMakeLists.txt, core/src/client/CMakeLists.txt, core/src/server/CMakeLists.txt, doc/example_app.md, doc/starters_guide.md, tools/CMakeLists.txt
Change cmake to accept CMAKE_INSTALL_PREFIX.
Add install prefix variable to top-level Makefile, so that installation prefix can be specified at build time. Default is set to /usr/local. Override with 'make INSTALL_PREFIX=/path/to/install/to.
=> cmake installation changes

api/examples/tutorials/Makefile, doc/example_app.md
Removed /usr from installed include and lib paths to match the new default.
Signed-off-by: Rory Latchem <rory.latchem@imgtec.com>
=> Update default install paths in tutorial examples

core/src/client/lwm2m_client_xml_handlers.c, core/src/common/ipc_session.c, core/src/common/lwm2m_bootstrap_config.c, core/src/common/lwm2m_util.c, core/src/common/lwm2m_util.h, core/src/server/lwm2m_server_xml_handlers.c
=> Added guards around Lwm2mCore_DebugPrintSockAddr which is not supported by CONTIKI

api/Makefile, api/doc/doxygen-err-filter.sh
=> Filter deprecation doxygen warnings to prevent build breaking with Ubuntu 15.10+.

api/tests/server/test_observe_operation.cc, api/tests/support/process.cc, ci/cppcheck.suppress, core/src/common/lwm2m_plaintext.c
=> Fix cppcheck-1.72 issues.

ci/ci-docker.sh
For example using CMAKE_OPTIONS to build variants of Awa.
=> Add docker override variables to permit customisation of build

core/src/common/dtls_abstraction_cyassl.c, core/src/common/lwm2m_tlv.c, core/src/common/lwm2m_tree_builder.c, core/src/common/lwm2m_types.h, core/src/common/lwm2m_util.h, core/src/erbium/er-coap.h
Adapt common and client modules for pic32 with MICROCHIP_PIC32 definition
Note: pic32 specific lwm2m_util + abstraction modules created for the Microchip Wifire (chipkit) are not included.
=> Add support for pic32 platform

core/src/client/lwm2m_bootstrap.c
For Erbium there is no 1s delay between the first and second bootstrap retry
after bootstrap failed. Removed the first request to ensure only one request send.
Signed-off-by: Rory Latchem <rory.latchem@imgtec.com>
=> Prevent duplicate retry on bootstrap failed

api/tests/client/test_client_objdefs_from_file.cc, core/src/bootstrap/lwm2m_bootstrap_server.c, core/src/client/awa_clientd.ggo, core/src/client/awa_clientd_cmdline.c, core/src/client/awa_clientd_cmdline.h, core/src/client/lwm2m_client.c
to enable loading of multiple object and resource definition files.
=> Support multiple instances of --objDefs/-o option with awa_clientd

CMakeLists.txt
=> Set default CoAP library as Erbium.

core/src/bootstrap/lwm2m_bootstrap.c
Init failed with gcc 4.8.2, use memset as workaround
Signed-off-by: Rory Latchem <rory.latchem@imgtec.com>
=> Fix init code for older gcc compiler

core/src/common/dtls_abstraction_cyassl.c
Adapt logging so DTLS session established can be seen on clients during startup
Signed-off-by: Rory Latchem <rory.latchem@imgtec.com>
=> Change log output from CyaSSL

CMakeLists.txt, api/CMakeLists.txt
Add option to turning off building examples (which is still on by default)
=> Add option to turning off building examples

core/src/common/dtls_abstraction_tinydtls.c
Change TinyDTLS abstraction as on Contiki,  function dtls_new_context can only be called once as it starts a process everytime
=> Change for TinyDTLS abstraction for Contiki

api/tests/server/test_observe_operation.cc, api/tests/server/test_write_operation.cc, ci/cppcheck.suppress, core/src/client/lwm2m_client_core.c
Change PUT/Replace on objects so it does not do delete/insert. Also add test cases to check observation is still notified when resources are updated by an object replace.
=> Change PUT/Replace on objects so it does not do delete/insert.

core/src/common/dtls_abstraction_gnutls.c
Signed-off-by: delmet <delmejt@gmail.com>
=> Change for older versions of GnuTLS that do not support AES-128-CCM-8

api/tests/server/test_write_operation.cc
Signed-off-by: Simon Thompson <simon.thompson@imgtec.com>
=> fix memory leak

api/python/ipc_lwm2m_server.py, api/python/tests/test_ipc_lwm2m_server.py
According to the docs the observe request needs an \<Observe/\> tag:
https://github.com/FlowM2M/AwaLWM2M/blob/master/doc/ipc.md#observe
=> Fix Python API's observe request

core/src/common/dtls_abstraction_tinydtls.c
If the PSK Identity is not set then application will crash while
trying to call strlen on NULL pointer. Check if PSK identity is
not null before using it.
Signed-off-by: <Michal.Kowalczyk@imgtec.com>
=> tinydtls: fix crash caused by null psk identity

api/python/ipc_core.py, api/python/ipc_lwm2m_client.py, api/python/ipc_lwm2m_server.py, ci/requirements.txt
Based on #305 
Removes the requirement for lxml, while also adding a requirement for the future package (only for iteritems for now). ElementTree is significantly slower than lxml, however it makes for an easier use out of the box on the Ci40. Future package can be easily installed via 'pip install future'
=> Python API: Make the API Python 2 & 3 compatible

CMakeLists.txt, Makefile, api/src/CMakeLists.txt, core/src/CMakeLists.txt, core/src/bootstrap/CMakeLists.txt, core/src/client/CMakeLists.txt, core/src/common/CMakeLists.txt, core/src/erbium/CMakeLists.txt, core/src/server/CMakeLists.txt, daemon/src/CMakeLists.txt, tools/CMakeLists.txt
Improve the build so that smaller binaries can be built (#330):
make DEBUG=0 will enable the release build in CMake, default build is debug with existing debug options.
=> Add release build to CMake

core/src/common/network_abstraction_linux.c
The sendto() function can fail because of  multiple conditions.
Currently we are handling few conditions. If there is an error due
to another condition, the process gets stuck in repeatedly trying
to call sendto() function and failing with the same error condition.
For example, when awa session is established and after that
network interface goes down(ex. ethernet cable is removed),
the sendto() fuction fails with error 'ENETUNREACH'. This error
is not handled and the process gets stuck in repeatedly calling
sendto() fuction. There are also other possible error conditions.
In this change handling all error conditions, so that process
does not get stuck in endless loop.
Ref: AWA-311
Signed-off-by: Pranit Tanaji Sirsat <Pranit.Sirsat@imgtec.com>
=> Handle sendto() function failure conditions

tools/tests/python/test_awa_server_write_attributes.py
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
=> Python 3.6 invalid escape sequence deprecation fixes

core/src/common/lwm2m_util_riot.c
Signed-off-by: Sean Kelly <seandtkelly@gmail.com>
=> Fix missing macro in RIOT utilities
