ci/jenkins.sh
=> Add support for branch coverage reporting.

core/src/client/lwm2m_client_xml_handlers.c
=> Fix debug message in GetRequest handler

.travis.yml, api/tests/CMakeLists.txt, core/tests/CMakeLists.txt, core/tests/test_xml.cc
=> Add travis yml

api/doc/template/mainpage.dox
=> Updated blurb on doxygen landing page

core/src/client/Makefile.client, core/src/client/lwm2m_static.c, core/src/common/Makefile.common
=> Updated makefiles for static api so that it builds for contiki

.travis.yml
=> Add command for travis-ci to run tests.

core/src/bootstrap/lwm2m_bootstrap.c, core/src/client/lwm2m_bootstrap.c, core/src/common/CMakeLists.txt, core/src/common/lwm2m_ipc.c, core/src/common/lwm2m_observers.c, core/src/common/lwm2m_result.c, core/src/common/lwm2m_result.h, core/src/common/lwm2m_types.h, core/src/common/lwm2m_xml_serdes.c, core/src/server/lwm2m_server_xml_handlers.c
=> Fix up include path for awa/static.h

api/tests-static/test_client.cc, core/src/client/lwm2m_static.c, core/src/common/lwm2m_definition.c, core/src/common/lwm2m_definition.h
This pull request adds support for AwaStaticClient_RegisterObject() and AwaStaticClient_RegisterResourceWithPointer(). 
I do however have some questions about the API in this regard.
=> Implement AwaStaticClient_RegisterResourceWithPointer

README.md
=> Add build/license badges to README

doc/coding_style.md
=> Updated coding_style.md - minor edit

api/examples/tutorials/.gitignore, api/examples/tutorials/Makefile, api/examples/tutorials/client-tutorial1.c, api/examples/tutorials/client-tutorial2.c, api/examples/tutorials/server-tutorial.c, api/examples/tutorials/static-client-tutorial1.c, api/examples/tutorials/static-client-tutorial2.c, doc/example_app.md
=> Add API tutorials as per documentation to api/example/tutorials

api/examples/tutorials/static-client-tutorial3.c
=> Added static client example using handlers.

api/examples/tutorials/static-client-tutorial1.c, api/examples/tutorials/static-client-tutorial2.c, api/examples/tutorials/static-client-tutorial3.c, api/include/awa/static.h, api/tests-static/test_client.cc, core/src/client/lwm2m_static.c, doc/example_app.md, tools/tests/python/test_awa_server_list_clients_multiple.py
=> Fix spelling of "CoAP".

Makefile, api/tests-static/test_client.cc
=> Add missing valgrind tests.

ci/jenkins.sh
=> Add docs to CI build.

ci/jenkins.sh, core/src/bootstrap/CMakeLists.txt, core/src/common/CMakeLists.txt, core/tests/CMakeLists.txt
=> Enable gcov for test_core_runner

api/include/awa/common.h, api/src/arrays.c, api/src/arrays.h, api/src/changeset.c, api/src/get_response.c, api/src/read_operation.c, api/src/response_common.c, api/src/response_common.h, api/src/string_array.c, api/tests/test_array_types.cc, api/tests/test_set_operation.cc, api/tests/test_write_operation.cc, core/src/client/lwm2m_client_core.c, core/src/common/lwm2m_bootstrap_config.c, core/src/common/lwm2m_object_store.c, core/src/common/lwm2m_prettyprint.c, core/src/common/lwm2m_tlv.c, core/src/common/lwm2m_tree_builder.c, core/src/common/lwm2m_xml_serdes.c, core/tests/test_lwm2m_tree_builder.cc, core/tests/test_object_store_interface.cc, tools/tools_common.c
Signed-off-by: Sean Kelly <Sean.Kelly@imgtec.com>
=> Rework core and API to use non-terminated strings

core/src/common/lwm2m_json.c, core/src/common/lwm2m_plaintext.c, core/tests/test_lwm2m_tree_builder.cc
=> Fix json and plaintext serialises not NULL terminating strings correctly

api/examples/tutorials/client-tutorial1.c, api/examples/tutorials/client-tutorial2.c, api/examples/tutorials/server-tutorial.c, api/examples/tutorials/static-client-tutorial1.c, api/examples/tutorials/static-client-tutorial2.c, api/examples/tutorials/static-client-tutorial3.c
Signed-off-by: Sean Kelly <Sean.Kelly@imgtec.com>
=> Add license to tutorials

api/doc/template/mainpage.dox
=> Update doxygen title.

api/tests-static/test_client.cc
Signed-off-by: Sean Kelly <Sean.Kelly@imgtec.com>
=> Fix valgrind error in Static API test

README.md
=> Valgrind PR CI testing.

README.md
=> Add Coverity Scan badge.

api/src/string_array.c, api/src/value.c, api/tests/support/process.cc, core/src/client/lwm2m_client_xml_handlers.c, core/tests/test_object_store_interface.cc
=> Fix some coverity issues raised in April 10th scan.

core/src/common/lwm2m_tlv.c
=> Fix buffer overrun detected by coverity

doc/userguide.md
Remove link to invalid document. Change example client names to more general names.
=> Minor documentation update.

api/python/common.py, tools/tests/python/test_awa_server_list_clients_multiple.py
=> Fix use of unittest's doCleanups() mechanism.

api/include/awa/client.h, api/include/awa/static.h
=> Documentation update.

CONTRIBUTORS
=> Added Tony and Rory to CONTRIBUTORS

api/tests/server/test_server_events.cc
=> Fix ClientUpdateEvent test.

api/tests/server/test_server_events.cc, api/tests/support/support.h
=> Fix Coverity issue 114167.

README.md, doc/Awa_Static_API.md, doc/developer_guide.md, doc/lwm2m_overview.md, doc/starters_guide.md, doc/userguide.md
I've performed a minor documentation review in prep for the major one - ironed out a few creases so we can stay on point.
=> Documentation review updates

api/python/overlord.py, api/src/arrays.c, api/tests/client/test_get_operation.cc, api/tests/client/test_set_operation.cc, api/tests/client/test_subscribe_operation.cc, api/tests/common/test_define_operation.cc, api/tests/server/test_execute_operation.cc, api/tests/server/test_list_clients_operation.cc, api/tests/server/test_observe_operation.cc, api/tests/server/test_read_operation.cc, api/tests/server/test_server_delete_operation.cc, api/tests/server/test_write_attributes_operation.cc, api/tests/server/test_write_operation.cc, api/tests/support/daemon.h, api/tests/support/process.cc, api/tests/support/process.h, api/tests/support/support.cc, api/tests/support/support.h
=> Speed up tests by removing conservative waits. Refer #165.

api/src/ipc.c, api/tests/server/test_observe_operation.cc, api/tests/server/test_server_events.cc, api/tests/server/test_server_notification.cc, api/tests/server/test_write_attributes_operation.cc, api/tests/static-client/test_static_api_with_pointer.cc, api/tests/support/static_api_support.h, api/tests/support/support.h
=> Additional test optimisations for #165.

api/include/awa/client.h, api/include/awa/error.h, api/include/awa/server.h, api/src/client_delete_operation.c, api/src/client_session.c, api/src/execute_operation.c, api/src/get_operation.c, api/src/ipc.c, api/src/list_clients_operation.c, api/src/read_operation.c, api/src/server_delete_operation.c, api/src/server_session.c, api/src/session_common.c, api/src/session_common.h, api/src/set_operation.c, api/src/write_attributes_operation.c, api/src/write_operation.c, api/tests/client/test_client_session.cc, api/tests/common/test_session_common.cc, api/tests/server/test_observe_operation.cc, api/tests/server/test_read_operation.cc, api/tests/server/test_server_session.cc, api/tests/server/test_write_attributes_operation.cc, api/tests/server/test_write_operation.cc
Modify tests to use this function to improve test speed.
=> Add API functions to set a session's default Connect/Disconnect timeout

Makefile, ci/Dockerfile, ci/requirements.txt
=> Add Dockerfile creation.

doc/docker.md
A little rephrasing and the addition of the IMG logo
=> Update docker.md for styling and branding

ci/ci.sh
=> Filter out coverage of _cmdline.c files.

core/src/bootstrap/lwm2m_bootstrap_server.c, core/src/client/lwm2m_client.c, core/src/common/coap_abstraction.h, core/src/common/coap_abstraction_contiki.c, core/src/common/coap_abstraction_erbium.c, core/src/common/coap_abstraction_libcoap.c, core/src/common/dtls_abstraction.h, core/src/common/dtls_abstraction_cyassl.c, core/src/common/dtls_abstraction_dummy.c, core/src/common/dtls_abstraction_gnutls.c, core/src/server/lwm2m_server.c
=> Add reporting of CoAP and DTLS libraries to daemons.

api/tests/CMakeLists.txt, api/tests/server/test_server_objdefs_from_file.cc, api/tests/support/daemon.h, api/tests/support/file_resource.h, api/tests/support/process.cc, api/tests/support/process.h, api/tests/support/support.h, core/src/client/lwm2m_client.c, core/src/client/lwm2m_client_xml_handlers.c, core/src/client/lwm2m_client_xml_handlers.h, core/src/common/CMakeLists.txt, core/src/common/dtls_abstraction_cyassl.c, core/src/common/lwm2m_definition.c, core/src/common/lwm2m_xml_interface.h, core/src/common/objdefs.c, core/src/common/objdefs.h, core/src/server/awa_serverd.ggo, core/src/server/awa_serverd_cmdline.c, core/src/server/awa_serverd_cmdline.h, core/src/server/lwm2m_server.c, core/src/server/lwm2m_server_xml_handlers.c, doc/example_app_static_api.md, doc/object_definition_files.md, doc/starters_guide.md, doc/userguide.md
Implement server daemon loading of object definition files before accepting client registrations. See #200.
=> Server objdef loading

CMakeLists.txt, config/localhost-secure.bsc, core/src/bootstrap/lwm2m_bootstrap_server.c, core/src/client/awa_clientd.ggo, core/src/client/awa_clientd_cmdline.c, core/src/client/awa_clientd_cmdline.h, core/src/client/lwm2m_client.c, core/src/common/coap_abstraction_erbium.c, core/src/common/dtls_abstraction_gnutls.c, core/src/common/network_abstraction.h, core/src/common/network_abstraction_linux.c, core/src/server/lwm2m_server.c
=> Add additional DTLS support

ci/update-docs.sh
=> Add script for updating docs repository.

core/src/common/objdefs.c
=> Fix Coverity issue 130249.

core/src/common/coap_abstraction_erbium.c
=> For erbium make sure coap message id is random

core/src/client/lwm2m_bootstrap.c, core/src/client/lwm2m_registration.c, core/src/common/coap_abstraction.h, core/src/common/coap_abstraction_contiki.c, core/src/common/coap_abstraction_erbium.c, core/src/common/coap_abstraction_libcoap.c, core/src/common/dtls_abstraction.h, core/src/common/dtls_abstraction_cyassl.c, core/src/common/dtls_abstraction_dummy.c, core/src/common/dtls_abstraction_gnutls.c, core/src/common/dtls_abstraction_tinydtls.c
=> Add support to reset DTLS sessions

doc/developer_guide.md
Signed-off-by: Chris Dewbery <chris.dewbery@gmail.com>
=> Fix reference to IPC documentation

core/src/client/Makefile.client
=> Fix contiki makefile for removed ojects

core/src/common/dtls_abstraction_gnutls.c
=> Add compiler error if GnuTLS does not support DTLS

core/src/common/coap_abstraction_libcoap.c, core/src/common/lwm2m_util_contiki.c, core/src/common/lwm2m_util_linux.c, core/src/common/network_abstraction_linux.c, tools/awa-server-write.c, tools/awa-server-write.ggo, tools/awa-server-write_cmdline.c, tools/awa-server-write_cmdline.h, tools/tests/python/test_awa_server_write.py
Change comparison on addresses to also check ports (See issue #269)
Also added replace option to server write tool (so can test PUT operations), so was able to test above issue more easily
=> Change comparison on addresses to also check ports (See issue #269)

core/src/common/lwm2m_util_linux.c
=> Fix coverity issue 140813

README.md
Signed-off-by: David Antliff <david.antliff@gmail.com>
=> Add NZOSA news. Add origin statement.

core/src/common/network_abstraction_contiki.c
=> Make contiki version of function NetworkAddress_New consistent with linux one

core/src/common/lwm2m_bootstrap_config.c
=> Ignore blank lines in bootstrap config files

core/src/client/lwm2m_bootstrap.c
This should address the issue raised in #298
=> Fix for a potential buffer overflow during the bootstrap process

.gitignore
Signed-off-by: Francois Berder <francois.berder@imgtec.com>
=> gitignore: Ignore generated .cmake

.travis.yml
Needed by https://github.com/FlowM2M/AwaLWM2M/pull/324
=> Update travis.yml to use pip's requirements.txt to install Python dependencies

api/examples/tutorials/static-client-tutorial1.c, api/examples/tutorials/static-client-tutorial2.c, api/examples/tutorials/static-client-tutorial3.c, core/src/client/lwm2m_static.c, daemon/src/bootstrap/awa_bootstrapd_cmdline.c, daemon/src/bootstrap/awa_bootstrapd_cmdline.h, daemon/src/client/awa_clientd.ggo, daemon/src/client/awa_clientd_cmdline.c, daemon/src/client/awa_clientd_cmdline.h, daemon/src/client/lwm2m_client.c, doc/docker.md
also rebuilt cmdline for bootstrap/clientd using slightly newer gengetopt
Signed-off-by: Matt Vinall <Matt.Vinall@imgtec.com>
=> awa_clientd and static API bind to random port

core/src/common/network_abstraction_contiki.c
There has been some issues with observes due to the way ports were parsed. I standarised it so that ports are always passed as integers in whatever format the platform prefers, and they are converted to network format just before sending/reading. This means that until we send we do not really care about what format the ports should be saved in.
=> Fix Contiki abstraction layer mixing different format for storing ports

config/localhost.bsc, core/src/common/dtls_abstraction_tinydtls.c
This reverts commit 66e67889a18031d3d0579f30287217e9c47dd35a.
Signed-off-by: Francois Berder <francois.berder@imgtec.com>
=> Revert debug commits from RIOT port pull request
